import torch
import torch.nn as nn


class squeezenet(nn.Module):
    def __init__(self):
        super(squeezenet, self).__init__()
        self.layer1 = torch.nn.Conv2d(in_channels=3, kernel_size=1, out_channels=96, stride=2)
        self.layer2 = torch.nn.ConstantPad2d(padding=3, value=124)
        self.layer3 = torch.nn.Conv2d(in_channels=96, kernel_size=1, out_channels=16, stride=1, bias=True)
        self.layer4 = torch.nn.ReLU(inplace=True)
        self.layer5 = torch.nn.ReplicationPad2d(padding=1)
        self.layer6 = torch.nn.ReLU(inplace=True)
        self.layer7 = torch.nn.ReplicationPad2d(padding=1)
        self.layer8 = torch.nn.ReLU6(inplace=False)
        self.layer10 = torch.nn.ReplicationPad2d(padding=(1, 8, 4, 7))
        self.layer11 = torch.nn.ReLU(inplace=True)
        self.layer12 = torch.nn.ZeroPad2d(padding=1)
        self.layer13 = torch.nn.LeakyReLU(inplace=True)
        self.layer14 = torch.nn.ReflectionPad2d(padding=1)
        self.layer15 = torch.nn.Hardswish(inplace=False)
        self.layer17 = torch.nn.ConstantPad2d(padding=(6, 2, 5, 2), value=224)
        self.layer18 = torch.nn.ReLU(inplace=True)
        self.layer19 = torch.nn.ReflectionPad2d(padding=1)
        self.layer20 = torch.nn.ReLU(inplace=False)
        self.layer21 = torch.nn.ZeroPad2d(padding=1)
        self.layer22 = torch.nn.ReLU(inplace=True)
        self.layer24 = torch.nn.AdaptiveAvgPool2d(output_size=1)
        self.layer25 = torch.nn.ConstantPad2d(padding=5, value=224)
        self.layer26 = torch.nn.ELU(alpha=0.2368488055965694, inplace=False)
        self.layer27 = torch.nn.ReplicationPad2d(padding=1)
        self.layer28 = torch.nn.SELU(inplace=True)
        self.layer29 = torch.nn.ZeroPad2d(padding=1)
        self.layer30 = torch.nn.ReLU(inplace=True)
        self.layer32 = torch.nn.Unfold(kernel_size=1, stride=4, dilation=(2, 6), padding=8)
        self.layer33 = torch.nn.ReLU(inplace=False)
        self.layer34 = torch.nn.ReflectionPad2d(padding=1)
        self.layer35 = torch.nn.ELU(alpha=0.9795990250223938, inplace=True)
        self.layer36 = torch.nn.ReplicationPad2d(padding=1)
        self.layer37 = torch.nn.SELU(inplace=True)
        self.layer39 = torch.nn.ZeroPad2d(padding=1)
        self.layer40 = torch.nn.ReLU6(inplace=False)
        self.layer41 = torch.nn.ConstantPad2d(padding=1, value=39)
        self.layer42 = torch.nn.ReLU(inplace=True)
        self.layer43 = torch.nn.ReflectionPad2d(padding=1)
        self.layer44 = torch.nn.Hardsigmoid(inplace=False)
        self.layer46 = torch.nn.ConstantPad2d(padding=1, value=83)
        self.layer47 = torch.nn.Hardswish(inplace=False)
        self.layer48 = torch.nn.ReflectionPad2d(padding=1)
        self.layer49 = torch.nn.ReLU(inplace=True)
        self.layer50 = torch.nn.ReplicationPad2d(padding=1)
        self.layer51 = torch.nn.Hardswish(inplace=False)
        self.layer53 = torch.nn.MaxPool2d(kernel_size=3, stride=2, ceil_mode=True)
        self.layer54 = torch.nn.ZeroPad2d(padding=3)
        self.layer55 = torch.nn.ELU(alpha=0.997527355581013, inplace=True)
        self.layer56 = torch.nn.ReflectionPad2d(padding=1)
        self.layer57 = torch.nn.Hardsigmoid(inplace=False)
        self.layer58 = torch.nn.ZeroPad2d(padding=1)
        self.layer59 = torch.nn.ELU(alpha=0.3090017118631754, inplace=False)
        self.layer61 = torch.nn.AdaptiveAvgPool2d(output_size=1)
        self.layer62 = torch.nn.ConstantPad2d(padding=-1, value=1.0)

    def forward(self, x):
        x = self.layer1(x)
        x = self.layer2(x)
        x = self.layer3(x)
        x = self.layer4(x)
        y1 = self.layer5(x)
        y1 = self.layer6(y1)
        y2 = self.layer7(x)
        y2 = self.layer8(y2)
        x = torch.cat([y1,y2], dim=-1)
        x = self.layer10(x)
        x = self.layer11(x)
        y1 = self.layer12(x)
        y1 = self.layer13(y1)
        y2 = self.layer14(x)
        y2 = self.layer15(y2)
        x = torch.cat([y1,y2], dim=-1)
        x = self.layer17(x)
        x = self.layer18(x)
        y1 = self.layer19(x)
        y1 = self.layer20(y1)
        y2 = self.layer21(x)
        y2 = self.layer22(y2)
        x = torch.cat([y1,y2], dim=-1)
        x = self.layer24(x)
        x = self.layer25(x)
        x = self.layer26(x)
        y1 = self.layer27(x)
        y1 = self.layer28(y1)
        y2 = self.layer29(x)
        y2 = self.layer30(y2)
        x = torch.cat([y1,y2], dim=-1)
        x = self.layer32(x)
        x = self.layer33(x)
        y1 = self.layer34(x)
        y1 = self.layer35(y1)
        y2 = self.layer36(x)
        y2 = self.layer37(y2)
        x = torch.cat([y1,y2], dim=-1)
        x = self.layer39(x)
        x = self.layer40(x)
        y1 = self.layer41(x)
        y1 = self.layer42(y1)
        y2 = self.layer43(x)
        y2 = self.layer44(y2)
        x = torch.cat([y1,y2], dim=-1)
        x = self.layer46(x)
        x = self.layer47(x)
        y1 = self.layer48(x)
        y1 = self.layer49(y1)
        y2 = self.layer50(x)
        y2 = self.layer51(y2)
        x = torch.cat([y1,y2], dim=-1)
        x = self.layer53(x)
        x = self.layer54(x)
        x = self.layer55(x)
        y1 = self.layer56(x)
        y1 = self.layer57(y1)
        y2 = self.layer58(x)
        y2 = self.layer59(y2)
        x = torch.cat([y1,y2], dim=-1)
        x = self.layer61(x)
        x = self.layer62(x)
        return x


def go():
    model = squeezenet()
    x = torch.randn(3, 3, 244, 244)
    y = model(x)
    return model
