from Tools.Assembler import Assembler, Bssembler


# a = Assembler("lenet", 2, 50, "lenet_t")
# a.start()
# a = Assembler("mobilenet", 2, 50, "mobilenet_t")
# a.start()
# a = Assembler("squeezenet", 2, 50, "squeezenet_t")
# a.start()
# a = Assembler("alexnet", 2, 50, "alexnet_t")
# a.start()
# a = Assembler("pointnet", 2, 50, "pointnet_t")
# a.start()
# a = Assembler("vgg19", 2, 50, "vgg19_t")
# a.start()
# a = Assembler("googlenet", 2, 50, "googlenet_t")
# a.start()
a = Assembler("LSTM", 2, 50, "LSTM_t")
# a.start()
# b = Bssembler("lenet", "ltb")
# b.start()
# a = Assembler("resnet18", 2, 50, "resnet18_t")
a.start()
